require("mini.comment").setup()
require("mini.cursorword").setup()
require("mini.hipatterns").setup()
require("mini.indentscope").setup()
require("mini.pairs").setup()
-- require("mini.files").setup()
require("mini.statusline").setup()
require("mini.ai").setup()
